--5
CREATE DATABASE [OnlineShop]

USE [OnlineShop]

CREATE TABLE [ItemsTypes](
	[ItemTypeID] INT IDENTITY PRIMARY KEY,
	[Name] VARCHAR(50) UNIQUE NOT NULL 
)

CREATE TABLE [Items](
	[ItemID] INT IDENTITY PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	[ItemTypeID] INT FOREIGN KEY REFERENCES [ItemsTypes]([ItemTypeID]) NOT NULL
)

CREATE TABLE [Cities](
	[CityID] INT IDENTITY PRIMARY KEY,
	[Name] VARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE [Customers](
	[CustomerID] INT IDENTITY PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	[Birthday] DATE NOT NULL,
	[CityID] INT FOREIGN KEY REFERENCES [Cities]([CityID])
)

CREATE TABLE [Orders](
	[OrderID] INT IDENTITY PRIMARY KEY,
	[CustomerID] INT FOREIGN KEY REFERENCES [Customers]([CustomerID]) NOT NULL
)

CREATE TABLE [OrderItems](
	[OrderID] INT FOREIGN KEY REFERENCES [Orders]([OrderID]),
	[ItemID] INT FOREIGN KEY REFERENCES [Items]([ItemID]),
	PRIMARY KEY([OrderID], [ItemID])
)





DROP TABLE [ItemsTypes]
DROP TABLE [OrderItems]
DROP TABLE [Items]
DROP TABLE [Cities]
DROP TABLE [Customers]
DROP TABLE [Orders]